name: Publish
on:
  push:
    branches: main
    paths:
      - '.github/workflows/publish.yml'
      - 'content/**'
jobs:
  publish:
    name: ðŸ”¥ Publishing content
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Generate KV data
        run: npx workaholic build content.json
      - name: Publish Content
        run: npx workaholic publish content.json
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
